### ISSUE TITLE
cudnnv5 support?

### ISSUE THREAD

**Issue by SJTUzhanglj** [tqchen/mxnet-gan#1]
F:\mxnet\example\mxnet-gan\example>python gan_cifar10.py
[14:03:32] F:\mxnet\dmlc-core\include\dmlc/logging.h:235: [14:03:32] F:\mxnet\src\operator\cudnn_batch_norm.cc:20: CuDNNBatchNorm is merged into BatchNorm for cudnn version above v5.Use the later instead.
Traceback (most recent call last):
  File "gan_cifar10.py", line 32, in <module>
    code_shape=rand_shape)
  File "..\mxgan\module.py", line 89, in **init**
    symbol_generator, context, code_shape)
  File "..\mxgan\module.py", line 18, in **init**
    self.modG.bind(data_shapes=[("code", code_shape)])
  File "F:\mxnet\python\mxnet\module\module.py", line 262, in bind
    fixed_param_names=self._fixed_param_names)
  File "F:\mxnet\python\mxnet\module\executor_group.py", line 102, in __init__
    self.bind_exec(data_shapes, label_shapes, shared_group)
  File "F:\mxnet\python\mxnet\module\executor_group.py", line 130, in bind_exec
    self.execs.append(self._bind_ith_exec(i, data_shapes, label_shapes, shared_group))
  File "F:\mxnet\python\mxnet\module\executor_group.py", line 419, in _bind_ith_exec
    grad_req=grad_req, shared_exec=shared_exec)
  File "F:\mxnet\python\mxnet\symbol.py", line 839, in bind
    ctypes.byref(handle)))
  File "F:\mxnet\python\mxnet\base.py", line 77, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [14:03:32] F:\mxnet\src\operator\cudnn_batch_norm.cc:20: CuDNNBatchNorm is merged into BatchNorm for cudnn version above v5.Use the later instead.

anything wrong with the mxnet version?

**Comment by tqchen** [comment]
change CUDNNBatchNorm to BatchNorm

**Comment by tqchen** [comment]
updated the code
